### ISSUE TITLE
El XML requiere tener el nodo <Signature> antes de firmarlo?

### ISSUE THREAD

**Issue by schweini** [enzojimenez/hacienda-firmador-php#3]
El firmador CRLibre agregaba el nodo Signature al firmar.
Su firmador hace eso, o hay que tenerlo en el XML de una vez? Si es asi, el nodo puede ser vacío, o debe llevar información para el firmado?

**Comment by JeanCarlosChavarriaHughes** [comment]
Hice una pruebas con un XML sin el nodo de Signature y funcionó. Creo que no hace falta, de hecho no debería tener el nodo vacío porque el firmador lo agrega.

Lo que estoy notando son dos detalles:
1. El nodo de firma dice v4, donde antes decía v4.2 en la URL del pdf.  `xades:Identifier `
2. Hace falta el parametro xmlns:ds al inicio del nodo. No sé si es required pero un ejemplo que ví firmado en otro sitio lo traía. `xmlns:ds="http://www.w3.org/2000/09/xmldsig#"` 

cc: @schweini

**Comment by enzojimenez** [comment]
@schweini en efecto, el nodo es agregado por el mismo firmador. Pero tampoco le hace daño ir vacio.

**Comment by enzojimenez** [comment]
@JeanCarlosChavarriaHughes 

Gracias por los comentarios, puede subir el ejemplo por favor?
Sin embargo, acá mis comentarios:

1. Se refiere a estos?:
https://github.com/enzojimenez/hacienda-firmador-php/blob/c3a12e432fd06aeefbbc7a67171ea19f6f89c8d3/xmlseclibs/src/XMLSecurityDSig.php#L289
https://github.com/enzojimenez/hacienda-firmador-php/blob/c3a12e432fd06aeefbbc7a67171ea19f6f89c8d3/xmlseclibs/src/XMLSecurityDSig.php#L296

2. Acá lo agrega. ¿ese?:
https://github.com/enzojimenez/hacienda-firmador-php/blob/c3a12e432fd06aeefbbc7a67171ea19f6f89c8d3/xmlseclibs/src/XMLSecurityDSig.php#L69

saludos,
Enzo.
